/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>


#ifndef _Included_com_omar_deathnote_mediaplay_devices_SimpleLame
#define _Included_com_omar_deathnote_mediaplay_devices_SimpleLame
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_omar_deathnote_mediaplay_devices_SimpleLame_init
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_omar_deathnote_audioplay_SimpleLame
 * Method:    encode
 * Signature: ([S[SI[B)I
 */
JNIEXPORT jint JNICALL Java_com_omar_deathnote_mediaplay_devices_SimpleLame_encode
  (JNIEnv *, jclass, jshortArray, jshortArray, jint, jbyteArray);

/*
 * Class:     com_omar_deathnote_audioplay_SimpleLame
 * Method:    flush
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_omar_deathnote_mediaplay_devices_SimpleLame_flush
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_omar_deathnote_audioplay_SimpleLame
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_omar_deathnote_mediaplay_devices_SimpleLame_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
